services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - jambuddy-network
    hostname: backend

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/frontend
  #   networks:
  #     - jambuddy-network

  postgres:
      image: postgres
      env_file:
        - ./backend/.env
      volumes:
        - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:

networks:
  jambuddy-network:
    driver: bridge