CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fname" varchar,
  "lname" varchar,
  "street" varchar,
  "street2" varchar,
  "city" varchar,
  "state" varchar,
  "zipcode" varchar,
  "phone" varchar,
  "email" varchar,
  "photo" varchar,
  "note" varchar,
  "created" timestamp
);

CREATE TABLE "UserInstrument" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" int,
  "instrumentid" int,
  "exp_level" int
);

CREATE TABLE "UserGenre" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" int,
  "genreid" int
);

CREATE TABLE "JamRequest" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" int,
  "instrumentid" int,
  "genreid" int,
  "location" varchar,
  "exp_level" int,
  "status" varchar,
  "created" timestamp
);

CREATE TABLE "JamResponse" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jrid" int,
  "userid" int,
  "created" timestamp,
  "note" text,
  "status" varchar
);

CREATE TABLE "ExperienceLevel" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar
);

CREATE TABLE "Instrument" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "type" varchar
);

CREATE TABLE "MusicGenre" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "genre" varchar
);

CREATE TABLE "UserReview" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" int,
  "reviewerid" int,
  "created" timestamp,
  "rating" int,
  "comment" text
);

CREATE TABLE "UserMedia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" int,
  "type" char,
  "location" varchar,
  "seconds" int
);

ALTER TABLE "UserInstrument" ADD FOREIGN KEY ("userid") REFERENCES "User" ("id");

ALTER TABLE "UserInstrument" ADD FOREIGN KEY ("instrumentid") REFERENCES "Instrument" ("id");

ALTER TABLE "UserInstrument" ADD FOREIGN KEY ("exp_level") REFERENCES "ExperienceLevel" ("id");

ALTER TABLE "UserGenre" ADD FOREIGN KEY ("userid") REFERENCES "User" ("id");

ALTER TABLE "UserGenre" ADD FOREIGN KEY ("genreid") REFERENCES "MusicGenre" ("id");

ALTER TABLE "JamRequest" ADD FOREIGN KEY ("userid") REFERENCES "User" ("id");

ALTER TABLE "JamRequest" ADD FOREIGN KEY ("instrumentid") REFERENCES "Instrument" ("id");

ALTER TABLE "JamRequest" ADD FOREIGN KEY ("genreid") REFERENCES "MusicGenre" ("id");

ALTER TABLE "JamRequest" ADD FOREIGN KEY ("exp_level") REFERENCES "ExperienceLevel" ("id");

ALTER TABLE "JamResponse" ADD FOREIGN KEY ("jrid") REFERENCES "JamRequest" ("id");

ALTER TABLE "JamResponse" ADD FOREIGN KEY ("userid") REFERENCES "User" ("id");

ALTER TABLE "UserReview" ADD FOREIGN KEY ("userid") REFERENCES "User" ("id");

ALTER TABLE "UserReview" ADD FOREIGN KEY ("reviewerid") REFERENCES "User" ("id");

ALTER TABLE "UserMedia" ADD FOREIGN KEY ("userid") REFERENCES "User" ("id");

