export const allStates = [
    { id: "Alabama", label: "AL" },
    { id: "Alaska", label: "AK" },
    { id: "Arizona", label: "AZ" },
    { id: "Arkansas", label: "AR" },
    { id: "California", label: "CA" },
    { id: "Colorado", label: "CO" },
    { id: "Connecticut", label: "CT" },
    { id: "Delaware", label: "DE" },
    { id: "Florida", label: "FL" },
    { id: "Georgia", label: "GA" },
    { id: "Hawaii", label: "HI" },
    { id: "Idaho", label: "ID" },
    { id: "Illinois", label: "IL" },
    { id: "Indiana", label: "IN" },
    { id: "Iowa", label: "IA" },
    { id: "Kansas", label: "KS" },
    { id: "Kentucky", label: "KY" },
    { id: "Louisiana", label: "LA" },
    { id: "Maine", label: "ME" },
    { id: "Maryland", label: "MD" },
    { id: "Massachusetts", label: "MA" },
    { id: "Michigan", label: "MI" },
    { id: "Minnesota", label: "MN" },
    { id: "Mississippi", label: "MS" },
    { id: "Missouri", label: "MO" },
    { id: "Montana", label: "MT" },
    { id: "Nebraska", label: "NE" },
    { id: "Nevada", label: "NV" },
    { id: "New Hampshire", label: "NH" },
    { id: "New Jersey", label: "NJ" },
    { id: "New Mexico", label: "NM" },
    { id: "New York", label: "NY" },
    { id: "North Carolina", label: "NC" },
    { id: "North Dakota", label: "ND" },
    { id: "Ohio", label: "OH" },
    { id: "Oklahoma", label: "OK" },
    { id: "Oregon", label: "OR" },
    { id: "Pennsylvania", label: "PA" },
    { id: "Rhode Island", label: "RI" },
    { id: "South Carolina", label: "SC" },
    { id: "South Dakota", label: "SD" },
    { id: "Tennessee", label: "TN" },
    { id: "Texas", label: "TX" },
    { id: "Utah", label: "UT" },
    { id: "Vermont", label: "VT" },
    { id: "Virginia", label: "VA" },
    { id: "Washington", label: "WA" },
    { id: "West Virginia", label: "WV" },
    { id: "Wisconsin", label: "WI" },
    { id: "Wyoming", label: "WY" },
  ];
  