# Generated by Django 4.1.5 on 2023-01-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exp_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.experiencelevel')),
            ],
        ),
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('lastlogin', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255, null=True)),
                ('note', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('reviewerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='jamrequestmodule.users')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=255)),
                ('seconds', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.experiencelevel')),
                ('instrumentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.instrument')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.musicgenre')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.users')),
            ],
        ),
        migrations.CreateModel(
            name='JamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('jrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.jamrequest')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.users')),
            ],
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='genreid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.musicgenre'),
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='instrumentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.instrument'),
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.users'),
        ),
    ]
