# Generated by Django 4.1.5 on 2023-02-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jamrequest',
            old_name='userid',
            new_name='profileid',
        ),
        migrations.RenameField(
            model_name='jamresponse',
            old_name='userid',
            new_name='profileid',
        ),
        migrations.RenameField(
            model_name='usergenre',
            old_name='userid',
            new_name='profileid',
        ),
        migrations.RenameField(
            model_name='userinstrument',
            old_name='userid',
            new_name='profileid',
        ),
        migrations.RenameField(
            model_name='usermedia',
            old_name='userid',
            new_name='profileid',
        ),
        migrations.RenameField(
            model_name='userreview',
            old_name='userid',
            new_name='profileid',
        ),
    ]
