# Generated by Django 3.2.17 on 2023-02-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilephoto',
            old_name='profile_id',
            new_name='profileid',
        ),
    ]
