# Generated by Django 4.1.5 on 2023-02-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0003_remove_profile_user_jamrequest_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
