# Generated by Django 4.1.5 on 2023-02-25 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0005_remove_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteJamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.jamrequest')),
                ('created', models.DateTimeField(auto_now_add=True)),                
            ],
        ),
    ]
