# Generated by Django 3.2.17 on 2023-03-02 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0007_userfavoriteprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamrequest',
            name='exp_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.experiencelevel'),
            preserve_default=False,
        ),
    ]
