# Generated by Django 3.2.17 on 2023-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0008_alter_jamrequest_exp_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instruments',
        ),
        migrations.AddField(
            model_name='profile',
            name='instrument',
            field=models.ManyToManyField(to='jamrequestmodule.Instrument'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genres',
        ),
        migrations.AddField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(to='jamrequestmodule.MusicGenre'),
        ),
    ]
