# Generated by Django 3.2.17 on 2023-03-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0009_auto_20230303_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instrument',
            new_name='instruments',
        ),
    ]
