# Generated by Django 3.2.17 on 2023-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0010_rename_instrument_profile_instruments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinstrument',
            name='exp_level',
        ),
        migrations.RemoveField(
            model_name='userinstrument',
            name='instrumentid',
        ),
        migrations.RemoveField(
            model_name='userinstrument',
            name='profileid',
        ),
        migrations.RemoveField(
            model_name='jamrequest',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='jamrequest',
            name='genreid',
        ),
        migrations.RemoveField(
            model_name='jamrequest',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='jamrequest',
            name='instrumentid',
        ),
        migrations.RemoveField(
            model_name='jamrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='genres',
            field=models.ManyToManyField(blank=True, to='jamrequestmodule.MusicGenre'),
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='jamrequestmodule.Instrument'),
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='zipcode',
            field=models.CharField(default=90210, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='jamrequest',
            name='exp_level',
        ),
        migrations.AddField(
            model_name='jamrequest',
            name='exp_level',
            field=models.ManyToManyField(blank=True, to='jamrequestmodule.ExperienceLevel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exp_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='exp_level',
            field=models.ManyToManyField(blank=True, to='jamrequestmodule.ExperienceLevel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, to='jamrequestmodule.MusicGenre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='jamrequestmodule.Instrument'),
        ),
        migrations.DeleteModel(
            name='UserGenre',
        ),
        migrations.DeleteModel(
            name='UserInstrument',
        ),
    ]
