# Generated by Django 3.2.17 on 2023-03-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0014_remove_jamrequest_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='jamresponse',
            name='status',
        ),
        migrations.AlterField(
            model_name='jamrequest',
            name='status',
            field=models.CharField(default='Open', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='clips',
            field=models.ManyToManyField(blank=True, to='jamrequestmodule.Clips'),
        ),
    ]
