# Generated by Django 3.2.17 on 2023-03-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0015_auto_20230308_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
