# Generated by Django 3.2.17 on 2023-03-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0016_profile_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clips',
        ),
    ]
