# Generated by Django 3.2.17 on 2023-03-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamrequestmodule', '0017_remove_profile_clips'),
    ]

    operations = [
        migrations.AddField(
            model_name='clips',
            name='profile_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jamrequestmodule.profile'),
            preserve_default=False,
        ),
    ]
